In [13]:
import numpy as n

Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:
a) Addition of 2 in all the element

In [11]:
a = n.array([1,2,3,4,5])
a += 2
a

array([3, 4, 5, 6, 7])

b) Multiply 3 with all the elements

In [12]:
a *= 3
a

array([ 9, 12, 15, 18, 21])

c) Divide every element by 2

In [5]:
a //= 2
a

array([ 4,  6,  7,  9, 10])

Q.2 Questions on Basic NumPy Array:
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [6]:
arr = n.array([1,2,3,6,4,5])
arr[::-1]

array([5, 4, 6, 3, 2, 1])

b) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [7]:
x = n.array([1,2,3,4,5,1,2,1,1,1])
print("Mode of x: ",n.bincount(x).argmax())

Mode of x:  1


In [8]:
print("Maximum frequency of mode of array: ",n.bincount(x).max())

Maximum frequency of mode of array:  5


In [9]:
y=n.array([1,1,1,2,3,4,2,4,3,3,])
b=n.bincount(y)
maximum=max(b)
print("Mode of y: ",end="")
for i in range(len(b)):
    if b[i]==maximum:
        print(i,end=" ")
print()
print("Maximum frequency of mode of array: ",n.bincount(y).max())

Mode of y: 1 3 
Maximum frequency of mode of array:  3


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:
a) Access 1st row, 2nd column
b) Access 3rd row, 1st column

In [10]:
arr=n.array([[10,20,30],[40,50,60],[70,80,90]])
print("Element at first row second column: ",arr[0,1])
print("Element at third row first column: ",arr[2,0])

Element at first row second column:  20
Element at third row first column:  70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [14]:
Jasmine = n.linspace(10,100,25)
print("Original Array: ",Jasmine)
print("Dimension of array: ",Jasmine.ndim)
print("Shape of array: ",Jasmine.shape)
print("Total no. of elements of Array",Jasmine.size)
print("Datatype of array: ",Jasmine.dtype)
print("Size of array(Bytes): ",Jasmine.itemsize*Jasmine.size)
print("Transpose of array using reshape: ",Jasmine.reshape(Jasmine.size,1))
print("Transpose using attribute T: ",Jasmine.T)

Original Array:  [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimension of array:  1
Shape of array:  (25,)
Total no. of elements of Array 25
Datatype of array:  float64
Size of array(Bytes):  200
Transpose of array using reshape:  [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using attribute T:  [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.

In [23]:
UCS420_Jasmine = n.array([10,20,30,40,50,60,70,80,90,15,20,35]).reshape(3,4)
print("Original array: ",UCS420_Jasmine)
print("Mean of array: ",n.mean(UCS420_Jasmine))
print("Median of array: ",n.median(UCS420_Jasmine))
print("Max of array: ",n.max(UCS420_Jasmine))
print("Min of array: ",n.min(UCS420_Jasmine))
print("Unique of elements of array: ",n.unique(UCS420_Jasmine))
Reshaped_UCS420_Jasmine=UCS420_Jasmine.reshape(4,3)
print("Reshaped array(4,3):", Reshaped_UCS420_ Jasmine)
Resized_UCS420_Jasmine=n.resize(UCS420_Jasmine,(2,3))
print("Resized array(2,3): ",Resized_UCS420_Jasmine)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3356309460.py, line 9)