---------------------------------------------------------------------------------------------------------------------------------------------
Implementing logistic regression on Iris Dataset:
---------------------------------------------------------------------------------------------------------------------------------------------

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

---------------------------------------------------------------------------------------------------------------------------------------------
Loading the dataset and checking if it is loaded successfully

---------------------------------------------------------------------------------------------------------------------------------------------

In [2]:
iris = datasets.load_iris()
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['target'] = iris.target
print(df.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  


---------------------------------------------------------------------------------------------------------------------------------------------
Storing features and targets in two variables X and Y and further standardizing the data

---------------------------------------------------------------------------------------------------------------------------------------------

In [3]:
X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

---------------------------------------------------------------------------------------------------------------------------------------------
Initializing and training the model

---------------------------------------------------------------------------------------------------------------------------------------------

In [6]:
model = LogisticRegression(multi_class='ovr', solver='liblinear')
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

# The above functions were throwing some warnings that these functions would be removed in the newer versions, therefore ignoring 
# warnings using the warnings.filterwarnings() method
# import warnings
# warnings.filterwarnings("ignore")

---------------------------------------------------------------------------------------------------------------------------------------------
Evaluating the model

---------------------------------------------------------------------------------------------------------------------------------------------

In [5]:
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.83

Confusion Matrix:
[[10  0  0]
 [ 0  6  4]
 [ 0  1  9]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.86      0.60      0.71        10
           2       0.69      0.90      0.78        10

    accuracy                           0.83        30
   macro avg       0.85      0.83      0.83        30
weighted avg       0.85      0.83      0.83        30

