In [2]:
import numpy as np
a=np.array([1,2,3,4,5])
print("Original array: ",a)
print("Addition of 2 in all the elements: ",a+2)
print("Multiplication of 3 in all the elements: ",a*3)
print("Division by 2 in all the elements: ",a/2)

Original array:  [1 2 3 4 5]
Addition of 2 in all the elements:  [3 4 5 6 7]
Multiplication of 3 in all the elements:  [ 3  6  9 12 15]
Division by 2 in all the elements:  [0.5 1.  1.5 2.  2.5]


In [4]:
a=np.array([1,2,3,6,4,5])
print("Original array: ",a)
print("Reversed array: ",np.flip(a))
x=np.array([1,2,3,4,5,1,2,1,1,1])
print("Array x: ",x)
print("Mode of x: ",np.bincount(x).argmax())
print("Maximum frequency of mode of array: ",np.bincount(x).max())
y=np.array([1,1,1,2,3,4,2,4,3,3,])
print("Array y: ",y)
b=np.bincount(y)
maximum=max(b)
print("Mode of y: ",end="")
for i in range(len(b)):
    if b[i]==maximum:
        print(i,end=" ")
print()
print("Maximum frequency of mode of array: ",np.bincount(y).max())

Original array:  [1 2 3 6 4 5]
Reversed array:  [5 4 6 3 2 1]
Array x:  [1 2 3 4 5 1 2 1 1 1]
Mode of x:  1
Maximum frequency of mode of array:  5
Array y:  [1 1 1 2 3 4 2 4 3 3]
Mode of y: 1 3 
Maximum frequency of mode of array:  3


In [6]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print("Array: ",arr)
print("Element at first row second column: ",arr[0,1])
print("Element at third row first column: ",arr[2,0])

Array:  [[10 20 30]
 [40 50 60]
 [70 80 90]]
Element at first row second column:  20
Element at third row first column:  70


In [8]:
Jasmine=np.linspace(10,100,25)
print("Original Array: ",Jasmine)
print("Dimension of array: ",Jasmine.ndim)
print("Shape of array: ",Jasmine.shape)
print("Total no. of elements of Array",Jasmine.size)
print("Datatype of array: ",Jasmine.dtype)
print("Size of array(Bytes): ",Jasmine.itemsize*Jasmine.size)
print("Transpose of array using reshape: ",Jasmine.reshape(Jasmine.size,1))
print("Transpose using attribute T: ",Jasmine.T)

Original Array:  [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimension of array:  1
Shape of array:  (25,)
Total no. of elements of Array 25
Datatype of array:  float64
Size of array(Bytes):  200
Transpose of array using reshape:  [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using attribute T:  [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [9]:
ucs420_Jasmine=np.array([10,20,30,40,50,60,70,80,90,15,20,35]).reshape(3,4)
print("Original array: ",ucs420_Jasmine)
print("Mean of array: ",np.mean(ucs420_Jasmine))
print("Median of array: ",np.median(ucs420_Jasmine))
print("Max of array: ",np.max(ucs420_Jasmine))
print("Min of array: ",np.min(ucs420_Jasmine))
print("Unique of elements of array: ",np.unique(ucs420_Jasmine))
reshaped_ucs420_Jasmine=ucs420_Jasmine.reshape(4,3)
print("Reshaped array(4,3): ",reshaped_ucs420_Jasmine)
resized_ucs420_Jasmine=np.resize(ucs420_Jasmine,(2,3))
print("Resized array(2,3): ",resized_ucs420_Jasmine)

Original array:  [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean of array:  43.333333333333336
Median of array:  37.5
Max of array:  90
Min of array:  10
Unique of elements of array:  [10 15 20 30 35 40 50 60 70 80 90]
Reshaped array(4,3):  [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized array(2,3):  [[10 20 30]
 [40 50 60]]
